MyPersonalPage/MyPersonalPage/Controllers/ContactController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyPersonalPage.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(string name, string message, string email)
        {
            new EmailService().SendAsync(new IdentityMessage { Destination = ConfigurationManager.AppSettings["ContactEmail"], Subject = "Webpage Message from " + name + " (" + email + ")", Body = message });

            return View();
        }
    }
}

MyPersonalPage/MyPersonalPage/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MyPersonalPage.Models;
using PagedList;
using PagedList.Mvc;
using Microsoft.AspNet.Identity;
using System.IO;

namespace MyPersonalPage.Controllers
{  

    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        //[AllowAnonymous]
        //public ActionResult Index(int? page)
        //{
        //    int pageSize = 3;    // display three blog posts at a time on this page
        //    int pageNumber = (page ?? 1);
        //    return View(db.Posts.OrderByDescending(p => p.Created).ToPagedList(page ?? 1, pageSize));
        //}

        [AllowAnonymous]
        public ActionResult Index(int? page, string searchString)
        {
            var lastSearch = TempData["lastSearch"] as string;
            if (lastSearch != searchString)
            {
                page = 1;            
                TempData["lastSearch"] = searchString;
            }

            int pageSize = 3;    // display three blog posts at a time on this page
            int pageNumber = (page ?? 1);

            var searched = from p in db.Posts
                           where searchString == "" || searchString == null || 
                           p.Body.Contains(searchString) ||
                           p.Title.Contains(searchString) ||
                           p.Comments.Any(c => c.Body.Contains(searchString) || 
                               c.Author.DisplayName.Contains(searchString))
                           orderby p.Created descending
                           select p;

            ViewBag.found = searched.Count();

            //var searched = db.Posts.OrderByDescending(p => p.Created).ToPagedList(pageNumber, pageSize);
            
            ViewBag.searchString = searchString;

            return View(searched.ToPagedList(pageNumber, pageSize));
        }

        // GET: Posts
        public async Task<ActionResult> AdminIndex()
        {
            return View(await db.Posts.ToListAsync());
        }

        // GET: Posts/Details
        [AllowAnonymous]
        public ActionResult Details(string Slug)
        {
            if (String.IsNullOrWhiteSpace(Slug))
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.FirstOrDefault(p => p.Slug == Slug);
            if (post == null)
            {
                return HttpNotFound();
            }
            // sort comments in descending order
            post.Comments = post.Comments.OrderByDescending(p => p.Created).ToList();

            return View(post);
        }

        //// GET: Posts/CreateComment
        //public ActionResult CreateComment()
        //{
        //    return View();
        //}

        // POST: Posts/CreateComment
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> CreateComment([Bind(Include = "PostId,AuthorId,Created,Body")] Comment comment, string slug)
        {
            if (ModelState.IsValid)
            {
                if (String.IsNullOrWhiteSpace(comment.Body))
                {
                    ModelState.AddModelError("Body", "Missing Comment Text");
                    return RedirectToAction("Details", new { Slug = slug });
                }
                comment.Created = System.DateTimeOffset.Now;
                comment.AuthorId = User.Identity.GetUserId();

                db.Comments.Add(comment);
                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { Slug = slug });

            }
            return RedirectToAction("Details", new { Slug = slug });
        }



        // GET: Posts/Create
        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Create([Bind(Include = "Created,Title,Body,MediaUrl")] Post post, HttpPostedFileBase image)
        {
            if (image != null && image.ContentLength > 0)
            {
                // check the file name to make sure it's an image type
                var ext = Path.GetExtension(image.FileName);
                if (ext != ".png" && ext != ".jpg" && ext != ".jpeg")
                    ModelState.AddModelError("image", "Invalid format.");
            }


            if (ModelState.IsValid)
            {
                var Slug = StringUtilities.URLFriendly(post.Title);
                if (String.IsNullOrWhiteSpace(Slug))
                {
                    ModelState.AddModelError("Title", "Invalid title.");
                    return View(post);
                }
                if (db.Posts.Any(p => p.Slug == Slug))
                {
                    ModelState.AddModelError("Title", "The title must be unique.");
                    return View(post);
                }
                else
                {
                 ////relative server path
                 //var filePath = "/Uploads/blog/images/";
                 ////path on physical drive on the server
                 //var absPath = Server.MapPath("~" + filePath);
                 ////media Url for relative path
                 //post.MediaUrl = filePath + image.FileName;
                 ////save image
                 //image.SaveAs(Path.Combine(absPath, image.FileName));


                    post.Created = System.DateTimeOffset.Now;
                    post.Slug = Slug;

                    db.Posts.Add(post);
                    await db.SaveChangesAsync();
                    return RedirectToAction("Index");
                }
            }
            return View(post);
        }

        // GET: Posts/EditComment
        [Authorize(Roles = "Admin, Moderator")]
        public async Task<ActionResult> EditComment(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Comment comment = await db.Comments.FindAsync(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        // POST: Posts/EditComment
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Moderator")]
        //public async Task<ActionResult> Edit([Bind(Include = "Id,Created,Updated,Title,Body,MediaUrl,Slug")] Post post)
        public async Task<ActionResult> EditComment([Bind(Include = "Created,Id,Updated,UpdatedReason,AuthorId,Body,PostId")] Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Comments.Attach(comment);
                comment.Updated = System.DateTimeOffset.Now;

                db.Entry(comment).State = EntityState.Modified;

                Post post = db.Posts.Find(comment.PostId);

                await db.SaveChangesAsync();
                return RedirectToAction("Details", new { slug = post.Slug });
                //return View();
            }
            return View(comment);
        }


        // GET: Posts/Edit
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        //public async Task<ActionResult> Edit([Bind(Include = "Id,Created,Updated,Title,Body,MediaUrl,Slug")] Post post)
        public async Task<ActionResult> Edit([Bind(Include = "Id,Updated,Title,Body,MediaUrl")] Post post)
        {
            if (ModelState.IsValid)
            {
                db.Posts.Attach(post);                
                post.Updated = System.DateTimeOffset.Now;
                    
                db.Entry(post).Property(p => p.Body).IsModified = true;
                //db.Entry(post).Property(p => p.Title).IsModified = true;
                db.Entry(post).Property(p => p.Updated).IsModified = true;
                db.Entry(post).Property(p => p.MediaUrl).IsModified = true;
                    
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = await db.Posts.FindAsync(id);
            if (post == null)
            {
                return HttpNotFound();
            }

MyPersonalPage/MyPersonalPage/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Mark Gaines | Professional Portfolio</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/font-awesome.css">
    <link rel="stylesheet" href="~/Content/flexslider.css">
    <link rel="stylesheet" href="~/Content/designr-theme-cyan.css">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic,900" rel="stylesheet" type="text/css">
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="home" data-spy="scroll" data-target="#main-nav" data-offset="200">



    <!-- ==============================================
    MAIN NAV
    =============================================== -->
    <div id="main-nav" class="navbar navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
                    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                </button>

                <!-- ======= LOGO ========-->
                <a class="navbar-brand scrollto" href="/#home">MARK GAINES<br><span>Developer</span></a>
                @*@Html.ActionLink("MARK GAINES", "Index", "Home", null, null, "home", null, new { @class = "navbar-brand scrollto" });*@
                <!-- <a class="navbar-brand scrollto ir-logo" href="#">JOHN DOE<br><span>UI Designer</span></a> -->

            </div>

            <div id="site-nav" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="sr-only">
                        @Html.ActionLink("Home", "Index", "Home", null, null, "home", null, new { @class = "scrollto" })
                    </li>
                    <li>
                        @Html.ActionLink("What I Do", "Index", "Home", null, null, "services", null, new { @class = "scrollto" })
                    </li>
                    <li>
                        @Html.ActionLink("About Me", "Index", "Home", null, null, "about", null, new { @class = "scrollto" })
                    </li>
                    @*<li>
                        @Html.ActionLink("My Works", "Index", "Home", null, null, "portfolio", null, new { @class = "scrollto" })
                    </li>*@
                    <li>
                        @*@Html.ActionLink("Contact Me", "Index", "Contact", null, null, "contact", null, null)*@
                        @Html.ActionLink("Contact Me", "Index", "Contact", null, null, "contact", null, new { @class = "scrollto" })
                    </li>
                    <li>
                        @Html.ActionLink("Blog", "Index", "Posts")
                    </li>
                    <li> 
                        @Html.ActionLink("Java Script Demo", "JavaScriptDemo", "Home")
                    </li>
                </ul>
            </div><!--End navbar-collapse -->
        </div><!--End container -->
    </div><!--End main-nav -->

    
        @RenderBody()
    

 
    <!-- ==============================================
    FOOTER
    =============================================== -->
        <footer id="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 left-col">
                        <h1 class="small-logo">MARK GAINES<br><span>Developer</span></h1>
                        <ul class="footer-nav">
                            <li><a class="scrollto" href="/#home">Home</a></li>
                            <li><a class="scrollto" href="/#services">Services</a></li>
                            @*<li><a class="scrollto" href="/#portfolio">Portfolio</a></li>*@
                            <li><a class="scrollto" href="/#contact">Contact</a></li>
                        </ul>
                        <p>&copy;Copyright 2015 / All Rights Reserved</p>
                    </div>
                    <div class="col-sm-6 right-col">
                        <h2>Who Am I?</h2>
                        <p>I am a full stack developer who enjoys online digital and offline world. I make high quality graphics and clean html5 and css3 codes.</p>
                        <ul class="footer-nav">
                            <li><a href="https://github.com/markEGaines" class="icon"><i class="icon-github"></i>GitHub</a></li>
                            <li><a href="https://linkedin.com/in/markegaines" class="icon"><i class="icon-linkedin-sign"></i>LinkedIn</a></li>
                        </ul>
                    </div>
                </div><!-- End row -->
            </div><!-- End container -->
        </footer><!-- End footer -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script src='~/js/jquery.scrollto.js'></script>
    <script src='~/js/jquery.flexslider.min.js'></script>
    <script src='~/js/twitterFetcher_v10_min.js'></script>
    <script src='~/js/jquery.masonry.min.js'></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/jquery.easypiechart.js"></script>
    <script src="~/js/jquery.backstretch.min.js"></script>
    <script src="~/js/contact.js"></script>
    <script src="~/js/designr.js"></script>

    @*<script src="~/js/libs/shCore.js"></script>
    <script src="~/js/libs/shAutoloader.js"></script>
    <script type="text/javascript" src="~/js/libs/shBrushJScript.js"></script>
    <script type="text/javascript">
        SyntaxHighlighter.all()
    </script>*@

</body>
</html>

MyPersonalPage/MyPersonalPage/Views/Shared/_LayoutPlain.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Mark Gaines | Professional Portfolio</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/font-awesome.css">
    <link rel="stylesheet" href="~/Content/flexslider.css">
    <link rel="stylesheet" href="~/Content/designr-theme-cyan.css">

    <link rel="stylesheet" href="~/Content/shCore.css">
    <link rel="stylesheet" href="~/Content/shThemeDefault.css">

    <link href="https://fonts.googleapis.com/css?family=Lato:400,300,300italic,400italic,700,700italic,900" rel="stylesheet" type="text/css">
    @Scripts.Render("~/bundles/modernizr")

</head>
<body  data-spy="scroll" data-target="#main-nav" data-offset="200">

    <!-- ==============================================
    MAIN NAV
    =============================================== -->
    <div id="main-nav" class="navbar navbar-fixed-top scrolled">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#site-nav">
                    <span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
                </button>

                <!-- ======= LOGO ========-->
                <a class="navbar-brand scrollto" href="/#home">MARK GAINES<br><span>Developer</span></a>
                @*@Html.ActionLink("MARK GAINES", "Index", "Home", null, null, "home", null, new { @class = "navbar-brand scrollto" });*@
                <!-- <a class="navbar-brand scrollto ir-logo" href="#">JOHN DOE<br><span>UI Designer</span></a> -->

            </div>

            <div id="site-nav" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li class="sr-only">
                        @Html.ActionLink("Home", "Index", "Home", null, null, "home", null, new { @class = "scrollto" })
                    </li>
                    <li>
                        @Html.ActionLink("What I Do", "Index", "Home", null, null, "services", null, new { @class = "scrollto" })
                    </li>
                    <li>
                        @Html.ActionLink("About Me", "Index", "Home", null, null, "about", null, new { @class = "scrollto" })
                    </li>
                    @*<li>
                        @Html.ActionLink("My Works", "Index", "Home", null, null, "portfolio", null, new { @class = "scrollto" })
                    </li>*@
                    <li>
                        @Html.ActionLink("Contact Me", "Index", "Contact")
                    </li>
                    <li>
                        @Html.ActionLink("Blog", "Index", "Posts")
                    </li>
                    <li> 
                        @Html.ActionLink("Java Script Demo", "JavaScriptDemo", "Home")
                    </li>
                </ul>
            </div><!--End navbar-collapse -->
        </div><!--End container -->
    </div><!--End main-nav -->

    
        @RenderBody()
    

 
    <!-- ==============================================
    FOOTER
    =============================================== -->
        <footer id="main-footer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 left-col">
                        <h1 class="small-logo">MARK GAINES<br><span>Developer</span></h1>
                        <ul class="footer-nav">
                            <li><a class="scrollto" href="/#home">Home</a></li>
                            <li><a class="scrollto" href="/#services">Services</a></li>
                            @*<li><a class="scrollto" href="/#portfolio">Portfolio</a></li>*@
                            <li><a class="scrollto" href="/#contact">Contact</a></li>
                        </ul>
                        <p>&copy;Copyright 2015 / All Rights Reserved</p>
                    </div>
                    <div class="col-sm-6 right-col">
                        <h2>Who Am I?</h2>
                        <p>I am a full stack developer who enjoys online digital and offline world. I make high quality graphics and clean html5 and css3 codes.</p>
                        <ul class="footer-nav">
                            <li><a href="https://github.com/markEGaines" class="icon"><i class="icon-github"></i>GitHub</a></li>
                            <li><a href="https://linkedin.com/in/markegaines" class="icon"><i class="icon-linkedin-sign"></i>LinkedIn</a></li>
                        </ul>
                    </div>
                </div><!-- End row -->
            </div><!-- End container -->
        </footer><!-- End footer -->

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <script src='~/js/jquery.scrollto.js'></script>
    <script src='~/js/jquery.flexslider.min.js'></script>
    <script src='~/js/twitterFetcher_v10_min.js'></script>
    <script src='~/js/jquery.masonry.min.js'></script>
    <script src="~/js/waypoints.min.js"></script>
    <script src="~/js/jquery.easypiechart.js"></script>
    <script src="~/js/jquery.backstretch.min.js"></script>
    <script src="~/js/contact.js"></script>
    <script src="~/js/designr.js"></script>
    <script src="~/js/JavaScriptDemo.js"></script>

    <script src="~/js/libs/shCore.js"></script>
    <script src="~/js/libs/shBrushJScript.js"></script>
    <script src="~/js/libs/shAutoloader.js"></script>
    <script type="text/javascript">
        SyntaxHighlighter.all()
    </script>

</body>
</html>